### ISSUE TITLE
Wrong $PATH in init_ilcsoft.sh if $<SOFT>_HOME=/usr 

### ISSUE THREAD

**Issue by freidt** [iLCSoft/iLCInstall#12]
Hi,

I found an issue with the way init_ilcsoft.sh is assembled. This happens in ilcsoft.py in the function `makeInstall` (see [https://github.com/iLCSoft/iLCInstall/blob/master/ilcsoft/ilcsoft.py#L409](url) ).

For software which is found on the system the corresponding `$<SOFT>_HOME` is = `/usr`. In such a case, a `/usr/bin` is then prepended to `$PATH`. This shadows then custom packages which are also installed on the system whose environment was prepared above.

An example of a problematic `init_ilcsoft.sh` is shown below:
```
export ILCSOFT=/opt/EUTelescope/testing/v01-17-10
# -------------------------------------------------------------------- ---
# ---  Use the same compiler and python as used for the installation   ---
# -------------------------------------------------------------------- ---
export PATH=/usr/bin:/cvmfs/sft.cern.ch/lcg/releases/LCG_87/Python/2.7.10/x86_64-ubuntu1604-gcc54-opt/bin:${PATH}
export LD_LIBRARY_PATH=/usr/lib64:/usr/lib:/cvmfs/sft.cern.ch/lcg/releases/LCG_87/Python/2.7.10/x86_64-ubuntu1604-gcc54-opt/lib:${LD_LIBRARY_PATH}
#--------------------------------------------------------------------------------
#     Java
#--------------------------------------------------------------------------------
export JAVA_HOME="/usr"
export JDK_HOME="$JAVA_HOME"
export PATH="$JDK_HOME/bin:$PATH" ###### PROBLEM: /usr/bin
export LD_LIBRARY_PATH="$JDK_HOME/jre/lib/i386:$JDK_HOME/jre/lib"/i386/client:$LD_LIBRARY_PATH"
## Following part not relevant ...
```

This propblem can e.g. arise from hepdt, mysql, fastjet, pathfinder, raida, java, gsl, xercesc in /usr/bin.

A potential fix is to check whether `$<SOFT>_HOME` is equal to `/usr` in every separate installer in the 
corresponding `postCheckDeps(self)` function and omit changing `$PATH`. However, this would not prevent such issues in the future.

//EDIT: This also concerns `$LD_LIBRARY_PATH`

**Comment by petricm** [comment]
Resolved
