### ISSUE TITLE
Update scripts to python3

### ISSUE THREAD

**Issue by tmadlener** [iLCSoft/iLCInstall#132]
Some (most) of the scripts that automate parts of the release process are not python3 compatible. Parts could potentially be handled by `2to3` but I am afraid that still some more manual changes are necessary.

The question is: Do we need compatibility with both or can we drop python2 compatibility in the process?

**Comment by tmadlener** [comment]
Re-using this to keep track of other smaller things that should be addressed in the process:
- [ ] Ignore all but the first appearance of `BEGINRELEASENOTES` `ENDRELEASENOTES` in a PR. Currently all appearances are used and appended to the release notes as separate entries.

**Comment by tmadlener** [comment]
- [ ] the tagging script currently crashes when it doesn't find a `CMakeLists.txt` where it can update the version. Would be nice if this can be handled more gracefully.

**Comment by andresailer** [comment]
a) ignore all but ... you mean just take the block from the opening post of the PR, and not the comments, right? this was initially intentional, but with admins ability to edit the opening post this isn't needed
b) missing cmakelists: What would you like to happen? Error message and exit, warning and continue, something else?

**Comment by tmadlener** [comment]
> a) ignore all but ... you mean just take the block from the opening post of the PR, and not the comments, right?

Yes, exactly. Mainly, because it happened for the current release that it also picked up comments, that were just saying to put them into the opening post of the PR.

> b) missing cmakelists: What would you like to happen? Error message and exit, warning and continue, something else?

Also, this is mainly just a convenience thing, because it would then be possible to easily tag iLCInstall itself with the script. Currently that fails before the tag is made, because it can't find a CMakeLists.txt. Maybe leaving the default behavior as is, but having an additional command line flag to ignore the CMakeLists.txt is the best, so that you have to consciously make the choice.

**Comment by tmadlener** [comment]
I think after #143 all scripts should now be working with python3 as well.
