### ISSUE TITLE
dl.bintray.com not available anymore

### ISSUE THREAD

**Issue by AMontagu** [iLCSoft/iLCInstall#154]
Hello

I am trying to build the docker image and I have an error when it install boost:

```
Downloading of the tag v00-00-02 of repository iLCSoft/SIO /home/ilc/ilcsoft/boost
--2022-03-13 16:56:27--  https://dl.bintray.com/boostorg/release/1.71.0/source/boost_1_71_0.tar.gz
Resolving dl.bintray.com (dl.bintray.com)... 35.157.253.39
Connecting to dl.bintray.com (dl.bintray.com)|35.157.253.39|:443... connected.
Unable to establish SSL connection.
```

Seem that dl.bintray.com is not available anymore.

I traced back to this file:
https://github.com/iLCSoft/iLCInstall/blob/master/ilcsoft/boost.py

But what I doesn't understand is the Version class `if( Version( self.version ) > "1.76.0" ):` where Version come from ?

And as I am downloading the 1.71.0 version it should use boostorg.jfrog.io depending of the condition.

**Comment by AMontagu** [comment]
I manually copied a fixed version of boost.py and rerun the docker build.
These error appear after:

```
################################################################################
##### Compiling ROOT version 6.18.04...
################################################################################

   ----- adding additional commands to build_env.sh : 
 

   ----- adding additional command to build_env.sh test -r /home/ilc/ilcsoft/root/6.18.04/bin/thisroot.sh && . /home/ilc/ilcsoft/root/6.18.04/bin/thisroot.sh


*** ERROR in module [ ROOT ]: DEBUG INFO: {'PLATFORM': 'Linux - unknown', 'GCC_VERSION': 'gcc (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0', 'LSB_RELEASE': '', 'UNAME': 'Linux 3a13e2ac2182 5.13.0-35-generic #40~20.04.1-Ubuntu SMP Mon Mar 7 09:18:32 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux'}

*** ERROR in module [ ROOT ]: At least one of these files: ['/home/ilc/ilcsoft/root/6.18.04/lib/libCore.so', '/home/ilc/ilcsoft/root/6.18.04/lib64/libCore.so', '/home/ilc/ilcsoft/root/6.18.04/lib/libCore.dylib']
is required for using this installation of ROOT

Logfile for failed module: /home/ilc/ilcsoft/.ilcinstall-logs/release-base-2022-3-13_17-16.log
The command '/bin/sh -c ./ilcsoft-install -i --install-prefix ${ILCSOFT} -j ${compile_ncores} releases/${install_mode}/release-base.cfg' returned a non-zero code: 
```
Is it possible to have a version published on dockerhub with some example on how to use it ?

**Comment by EnginEren** [comment]
Hi @AMontagu, 

We have currently two docker images in dockerhub

1) iLCsoft **v02-01-pre** with Boost 1.71 

https://hub.docker.com/repository/docker/ilcsoft/ilcsoft-centos7-gcc8.2 

2) iLCsoft with spack installation with Boost 1.75

https://hub.docker.com/repository/docker/ilcsoft/ilcsoft-spack

**Comment by AMontagu** [comment]
hi @EnginEren 

Thank you for the fats reply.

Is one of these image is compatible with the new LCFIPlus ?

Okay I will wait for them to answer me. I think it's because it's installing an old version of root that doesn't have the required file. But I do not understand how the version are choosen so I can't fix it myself :/.

**Comment by EnginEren** [comment]
Hmm. What do you mean by "compatible"? 

In both images, LCFIPlus was installed _v00-08_ and _v00-10_ respectively

**Comment by AMontagu** [comment]
You answered me. I meant installed or at least with the correct dependencies to be installed.
Thank you again.

**Comment by tmadlener** [comment]
Hi @AMontagu,

> But I do not understand how the version are choosen so I can't fix it myself :/.

If you use `iLCInstall` to install ilcsoft, the versions (and build options) are defined in the following files (e.g. in this case for the latest `v02-02-03` release:)

- [releases/v02-02/release-versions.py](https://github.com/iLCSoft/iLCInstall/blob/master/releases/v02-02/release-versions.py) defines the versions of all packages and libraries
- [releases/v02-02/release-base.cfg](https://github.com/iLCSoft/iLCInstall/blob/master/releases/v02-02/release-base.cfg) defines the so called "base" packages, e.g. ROOT, boost, etc.
- [releases/v02-02/release-ilcsoft.cofg](https://github.com/iLCSoft/iLCInstall/blob/master/releases/v02-02/release-ilcsoft.cfg) defines all the iLCSoft packages, e.g. Marlin, LCIO, dd4hep, etc.

If you have access to `/cvmfs` and you only need the dependencies for LCFIPlus it is probably easiest to use a release from `/cvmfs/ilc.desy.de/sw/x86_64_gcc82_centos7/` and build LCFIPlus on top of that. There are also nightly builds available from
`/cvmfs/clicdp.cern.ch/iLCSoft/lcg/100/nightly/` which will always have the latest version of all the iLCSoft packgaes.

**Comment by AMontagu** [comment]
Yes I have access to /cvmfs but only on the lab computer. I wanted to use it in home office. So docker was the best approach to me (just downloading using and then deleting without have everything on my personal computer).

(I am new on all iLCSoft so I may have some notion missing)

/cvmfs is handled by Subversion right ? I have a grid certificate but I can't install the /cvmfs repo on my personnal computer.

On this page: https://ilcsoft.desy.de/portal/general_documentation/ the link [Link to svn repository containing Grid tools for the ILC Software](https://svnsrv.desy.de/viewvc/ilctools/gridtools/trunk/) Is outdated

I have found https://confluence.desy.de/display/grid/CVMFS+repositories but I have a .pem instead of a .pub.


This conversation is going out of the initial issue:
- Do you want me to create a subject somewhere else ?
- Do you want me to close this issue or to keep it open for the docker issues
1. --build-arg install_mode=LASTEST not working -> used --build-arg install_mode=v02-02
2. File boost.py not working as dl.bintray.com not available anymore
3. The installation of root no longer working in docker due to missing file /home/ilc/ilcsoft/root/6.18.04/lib/libCore.so

- At wich frequency the docker image are build ? Because if they are not build regularly and I can't build them myself it may raise some issue in my work for the next month. -> Are you recommended me to abandon docker and use my GRID certificate to use the release from the subversion directory ? If yes where can I find the documentation to successfully clone it with my pem certificate ? (I am more familiar with git than svn)

**Comment by tmadlener** [comment]
To install the CVMFS client on your local machine follow [these instructions](https://cvmfs.readthedocs.io/en/stable/cpt-quickstart.html#). In order to make iLCSoft releases available you will need to add `ilc.desy.de` and `sft.cern.ch` to the `CVMFS_REPOSITORIES` configuration. This will make all iLCsoft releases available to you locally **if you are running CentOS7 on your local computer**. The links you have provided mostly point (or should point) to how to use the grid, which is somewhat orthogonal to iLCSoft in general.

If you are not running CentOS7, we have prepared a docker image that has all the necessary cvmfs setup already done for you. Essentially, what you would do to start it is

```sh
docker run -it --privileged ilcsoft/ilcsoft-cvmfs-centos7
```
this will drop you into a shell where you can then setup the `v02-02-03` release like this:
```sh
source /cvmfs/ilc.desy.de/sw/x86_64_gcc82_centos7/v02-02-03/init_ilcsoft.sh
```
This gives you an environment which is essentially the same as the one you have on your lab computer.

Something that is not yet entirely clear to me is what you actually want to do with iLCSoft or LCFIPlus?

**Comment by AMontagu** [comment]
Okay I will try it this evening

I want to use LCFIPlus to make a reconstruction of simulated events (e+ e- -> b b~ and e+ e- -> c c~) using flavor tagging tools of LCFIPlus for the optimization of vertex detector for futur Higgs factory projects

**Comment by AMontagu** [comment]
So the docker image is working as expected but each command (Marlin, ddsim, ...) are very slow at first usage after running the container.

It's logical as it load all the shared library. 

I tried to copy all the /cvmfs folder from docker to the host to mount it as a volume without succes (ilc.desy.de and sft.cern.ch folder are copied but empty)

I also tried to build an other docker image from the first one but it seem that /cvmfs folder is mounted at run (as show in log:  `CernVM-FS: mounted cvmfs on /cvmfs/ilc.desy.de`) 

What is the best practice to avoid loading the shared libraries at every run ?

**Comment by tmadlener** [comment]
> What is the best practice to avoid loading the shared libraries at every run ?

CVMFS is in principle caching things, so after the first run this should no longer be an issue, unless you hit a shared library you haven't loaded before. The problem with the docker approach is that the cache lives inside your container as well, and once you exit that, the cache will be gone as well. So everytime you start the container again the caching will start from scratch.

An alternative to this is to install CVMFS locally onto your machine, and then bind-mount it into the container. In this way the container would not need CVMFS at all and the cache stays intact, even if you shut the container down. In order for this to work the image can't have CVMFS installed inside it! You would then launch along the lines of

```sh
docker run -it -v /cvmfs:/cvmfs:shared <your-centos7-image>
```

**Comment by AMontagu** [comment]
Hello

Sorry for the late answer. I have successfully used the docker. 

Some poitn if someone is reading this issue later:
- The error Fuse is not loaded in the console in not a problem if you are mounting cvmfs with docker volume.
- There is a cache dir that you can use to avoid installing cvmfs on your pc: /var/lib/cvmfs So you can so something like: `docker run -it -v /var/lib/cvmfs-docker:/var/lib/cvmfs <your-centos7-image>`
