### ISSUE TITLE
Major problem with tagging script

### ISSUE THREAD

**Issue by gaede** [iLCSoft/iLCInstall#21]
@andresailer I have made pre-releases with the tagging script for all packages shown in:
https://github.com/iLCSoft/iLCInstall/blob/master/releases/v01-19/tagging_v01-19.py
However it turns out the the script has actually made all tags *without* the -pre appended.
The releases are however named correctly. See for example here:
https://github.com/AIDASoft/DD4hep/releases
Of course ilcinstall is looking for the tags with -pre and not the release names.
Any idea how to fix this ?
Thanks, Frank.

**Comment by andresailer** [comment]
I've changed the associated tag for the recent releases to the tag with the same name as the release name. I.e. creating new tags and deleting the non-pre tags.
I'll fix the bug in the script now.

**Comment by andresailer** [comment]
Where there problems with the creation of the release notes? I saw you edited some of them manually.

**Comment by petricm** [comment]
What about that the notes sometimes appear in the `https://github.com/iLCSoft/package/releases` and sometimes they don't?

**Comment by andresailer** [comment]
Release notes are only taken from PRs since the last tag/release (including pre-releases), so if there is a pre-release tag there are no more release notes.
One could maybe parse the ReleaseNotes file to get all the release notes since the last full release and fill that into the release notes of the release.

**Comment by gaede** [comment]
@andresailer thanks a lot for fixing the tags !
I had some problems with the release notes, but mostly because I had tried to manually add some release notes for the time before the PR script was activated and then had issues with the interplay of the script and my manual edits. I guess this is the expected 'learning curve' for this new way of automatically tagging. One issue I have observed in this context:
- the script only gathers release notes from the last tag that was made in time and not the last tag that was made on the given branch
    - for LCIO I had made an intermediate tag on branch v02-07-05 for the release notes up to that point in time ( branched from the corresponding SHA) 
    - but then the script did not find any PRs in anymore ( it correctly did on a dry-run before I made the intermediate tag on the branch)
    - would be good if we could use all PRs on the the given branch (master) since the last release tag on that branch

- another issue I observed is that for some packages the script reported no error but the actuall tagging and updating of release notes did not occur on the web-page
    - for these packages I rerun the script manually for this package and then it worked...

Anyways, apart from the problems I had so far, the scripts are an excellent idea and once we made them a bit more robust and have learned how to correctly use them will allow for much more frequent releases !

**Comment by andresailer** [comment]
1) I'll see what can be done. The problem is the association of tags and branches cannot be accessed via the github api, so one cannot find out if a tag is on a branch.
2) Can you give an example log output, or which package this happened with? That sounds very strange

**Comment by gaede** [comment]
1. Ok, I see. We could probably live with this as is, but that implies that no manual tags are allowed on a package , unless one creates a pre-release tag with the script first, to get the release notes...
2. Sorry just miss-interpreted the log file - there indeed was an error at the end that had caused some packages not to be versioned ( just had seen the output of the package itself that had no error). So this was a user-problem...

**Comment by andresailer** [comment]
1. I think I can add an option to specify the last tag to use to find PRs instead of automatically finding the last tag. This can be used to ignore manually created tags.

**Comment by gaede** [comment]
@andresailer I think that would be a good idea - not that we will use it in general, as this should be done with the normal workflow of simply gathering the PRs from the last tag - but there will probably always be cases where one needs to do things manually.

**Comment by gaede** [comment]
@andresailer Please Help !
Something must have gone wrong with deleting the tags 6 days ago. I just run the script to make the final release tags for v01-19-02 and it turns out that some of the release tags are (much) older than the latest pre-release tags, e.g.:
- lcgeo v00-11 is 7 days old, v00-11-pre3 is a few hours old.
- DD4hep v00-21-pre is newer than v00-21  ( however same code, so no big issue )
- similar for lcio (v02-08-pre/v02-08)
- potentially more packages ...

I tried to manually delete the false v00-11 release for lcgeo on the web page - but this only deleted the release and not the tag, so after recreating the release v00-11 it used the existing tag from 7 days ago ...
Any idea, how this can be fixed, other than manually doing this in checked out repositories ( for all packages ) ?
Is there a way to delete all tags from a given list via the API ?
( Eventually we need a mechanism in the script that prevents making any -pre release tags for an already existing tag).

**Comment by gaede** [comment]
@andresailer I convinced myself that actually only lcgeo was a real problem - all the other packages seem to also have been tagged 6 days ago with the proper release tag when making the pre-releases, but no updates since then.
I have manually deleted the lcgeo tag v00-11 and re-created it with the current HEAD ( identicall to v00-11-pre3, except a fix to the release notes).
So we should be good to go for v01-19-02.

**Comment by andresailer** [comment]
> ( Eventually we need a mechanism in the script that prevents making any -pre release tags for an already existing tag).

This should already be the case. If nothing changed since the last tag nothing will be done by the script, unless the last tag was a pre-release tag and the new tag is the release tag.

**Comment by gaede** [comment]
I think I understand now, what had happened with the tags:  Github dates the releases to the last commit that was used for the tag - and not the date the tag was actually made. I had just made a manual tag for ILDConfig v01-19-02 and GitHub claims : " v01-19-02 gaede released this 12 days ago " . This is very confusing...

**Comment by andresailer** [comment]
I think all known issues are addressed in #25

**Comment by gaede** [comment]
Excellent, thanks. Let's see how it works when we make the next release soon...
