### ISSUE TITLE
Socket error connecting to github from ilcsoft-install

### ISSUE THREAD

**Issue by StrahinjaLukic** [iLCSoft/iLCInstall#40]
I am trying to use ilcsoft-install to install the ilcsoft release v01-19-03-p1.
I am encountering the following error message. It does not seem to depend which package is being downloaded. 

****************************** Downloading sources ******************************

********************************************************************************
*** Downloading sources for LCCD version v01-04...
********************************************************************************
Downloading from https://api.github.com/repos/iLCSoft/LCCD/git/refs/tags/v01-04
Traceback (most recent call last):
  File "./ilcsoft-install", line 106, in <module>
    ilcsoft.makeinstall()
  File "/opt/ilcsoft/iLCInstall/ilcsoft/ilcsoft.py", line 442, in makeinstall
    mod.downloadSources()
  File "/opt/ilcsoft/iLCInstall/ilcsoft/baseilc.py", line 751, in downloadSources
    elif 'message' not in json.loads(urllib.urlopen('https://api.github.com/repos/%s/%s/git/refs/tags/%s' % (self.download.gituser, self.download.gitrepo, self.version)).read()).keys():
  File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib/python2.7/urllib.py", line 208, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 437, in open_https
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1220, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 243, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 405, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [Errno 8] _ssl.c:510: EOF occurred in violation of protocol

**Comment by StrahinjaLukic** [comment]
In fact I am getting the same error when I try to connect using urllib.urlopen() to anywhere with https: protocol. I will now close this as it doesn't seem to be an issue of iLCinstall. But if anyone has a hint what could be the reason for such connection problems, many thanks in advance.

**Comment by andresailer** [comment]
Since version 2.7.12 python forces certificate verification for https requests.
Either install the certification authority certificates or try 
```
export PYTHONHTTPSVERIFY=0
```
before running ilcinstall

**Comment by StrahinjaLukic** [comment]
I replaced urllib by urllib2 in baseilc.py (in the import directive and the affected command in line 751), and it is happily downloading now. 

Doing web search I found a few discussions to the point that urllib2 handles ssl better than urllib, offering more sophisticated options etc. But in my case, the only necessary change was to simply use urllib2 in place of urllib. Maybe iLCinstall could be updated to use urllib2 after all?

**Comment by rete** [comment]
@gaede Is it fixed now ? Should we close this issue ?

**Comment by gaede** [comment]
No, nothing done so far - can you try and fix this ?

**Comment by rete** [comment]
@StrahinjaLukic @andresailer After a look on documentation I found : 
- When using urllib
  - python version > 2.7.9, urllib **does not** attempt to validate the server certificate of HTTPS URLs (https://docs.python.org/2/library/urllib.html)
- When using urllib2
  - python version > 2.7.9 : the function [urlopen()](https://docs.python.org/2/library/urllib2.html) can use a 'context' argument, in which we can specify whether to verifiy or not the certificate. 
  - Example of workaround : https://stackoverflow.com/a/28048260

The question is actually : do we want to check the server certificate or not ?

**Comment by StrahinjaLukic** [comment]
Sorry for my slow response. 

In the urllib documentation that you link, I read, "Changed in version 2.7.9: For HTTPS URIs, urllib performs all the neccessary certificate and hostname checks by default.", and "For Python versions **earlier** than 2.7.9, urllib does not attempt..."

To summarize all of the above posts:
1. urllib checks certificates by default, but the checks fail in some circumstances. The reason seems to be an outdated implementation. In my case, the downloads did not work for any https servers.
2. urllib2 checks certificates by default, has a better implementation of the checks. The simple change of urllib to urllib2 in baseilc.py allowed me to successfully install ilcsoft. The possibility to bypass the cert checks is interesting if one ever needs that, but that was not the case here.

So I would say that one gains something and loses nothing by switching from urllib to urllib2.
