### ISSUE TITLE
Xerces C sources location

### ISSUE THREAD

**Issue by rete** [iLCSoft/iLCInstall#58]
The address at which we download the Xerces C package as part of the base packages in ILCInstall is changing all the time. The url `http://www.apache.org/dist/xerces/c/3/sources/` contains only the latest version of the Xerces C library. The latest version, when this ticket was open was 3.2.2 and the current version in ILCInstall is 3.1.4.
This causes many problems:
- ILCInstall can't be installed without manually changing the XercesC version 
- We have no way to re-install an old tag of ILCSoft containing an old version of XercesC

Potential solution:
- find another source for this library that would persist with time
- download a few versions we are interested in and make them available from outside for ILCSoft installation

**Comment by andresailer** [comment]
https://github.com/apache/xerces-c/releases
