### ISSUE TITLE
CMake config setup bug

### ISSUE THREAD

**Issue by petricm** [iLCSoft/iLCInstall#80]
When @gaede fixed the cmakeconfig path here https://github.com/iLCSoft/iLCInstall/commit/e69a7d154ef2392ddc94b5e7b395174858698ab5#diff-43c7f15e4148cc1085c2974bcaf23412R90
```py
self.cmakeconfig = self.installPath + "/lib/Geant4-" + v  + "; " + self.installPath + "/lib64/Geant4-" + v 
```
a semicolon was introduced, but cmakeconfig is used in ilcsoft.py to set two things: 1. the bash script and 2. the cmake env https://github.com/iLCSoft/iLCInstall/blob/bacc1a298b427070d8f2a7923d5b295e26113d41/ilcsoft/ilcsoft.py#L282-L283 . With the intro semicolon it breaks the propper cmake setup.

The easiest fix is that you check in geant4.py which system it is and then set lib or lib64, but you cannot set both.

**Comment by rete** [comment]
Thanks @petricm  for the issue. Indeed this is wrong for the shell script.

We couldn't really sort out how to know whether Geant4 will install libraries in `lib` or `lib64`. The cmakeconfig is used before installing anything, so I can't grep for `lib` or `lib64` in the Geant4 installation directory. 

Do you know how we can guess that ?

**Comment by rete** [comment]
Digged a bit and found that they are using `GNUInstallDirs` in CMake:

https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html

This can be `lib` or `lib64` or even worse a path with some architecture...
So we need to guess it after it has been installed which goes against how build flow, the ILCSoft.cmake and ILCSoft.cmake.env.sh files being generated before running anything

**Comment by petricm** [comment]
Why don't you just do
```py
if platform.system() == "Darwin":
  lib
else:
  lib64
```

**Comment by rete** [comment]
On my ubuntu I have `lib` not `lib64`

**Comment by rete** [comment]
To complete my comment on GNUInstallDirs, here is the logic:

https://gitlab.kitware.com/cmake/cmake/blob/master/Modules/GNUInstallDirs.cmake#L204

**Comment by petricm** [comment]
I think geant4 relies on `CMAKE_SIZEOF_VOID_P` to decide

https://github.com/Geant4/geant4/blob/6aa23be5171b125c3363b5a4cfa00a57e524598b/environments/g4py/cmake/Modules/SetInstallPath.cmake

**Comment by rete** [comment]
Your link is in `environment/g4py/cmake/`. This one is in `cmake/`:

https://github.com/Geant4/geant4/blob/6aa23be5171b125c3363b5a4cfa00a57e524598b/cmake/Modules/G4CMakeSettings.cmake#L124

**Comment by petricm** [comment]
Then for the moment I suggest to do a replace of `;->:` in ilcsoft.py and leave geant4.py as is

**Comment by rete** [comment]
My first suggestion to Frank when we introduced this "fix" was to turn the geant4 `cmakeconfig` to a list and check in ilcsoft.py if we have a list and make a join

**Comment by petricm** [comment]
Fine with me, but please asap, as the nightly is broken because of this.

**Comment by andresailer** [comment]
What about
```diff
-f2.write( configpath + ':\\' + os.linesep )
+f2.write( configpath.replace(';', ':') + ':\\' + os.linesep )
```
?

**Comment by gaede** [comment]
+1

**Comment by petricm** [comment]
this is exactly what i meant with `;->:`

**Comment by rete** [comment]
+1 too

**Comment by rete** [comment]
I'll take care of it now

**Comment by petricm** [comment]
This did not solve the problem, Geant4 is still not found in the DD4hep compilation

https://gitlab.cern.ch/CLICdp/SoftwareConfigurations/iLCSoft/-/jobs/6428871

**Comment by rete** [comment]
Your job is loading the CMake cache from here:

/cvmfs/clicdp.cern.ch/iLCSoft/builds/nightly/x86_64-slc6-gcc62-opt/ILCSoft.cmake

which contents is:

```cmake
################################################################################
# Environment script generated by ilcsoft-install on Wed Nov 27 23:20:14 2019
# for the installation located at [ /cvmfs/clicdp.cern.ch/iLCSoft/builds/nightly/x86_64-slc6-gcc62-opt ]
################################################################################

SET( ILC_HOME "/cvmfs/clicdp.cern.ch/iLCSoft/builds/nightly/x86_64-slc6-gcc62-opt" CACHE PATH "Path to ILC Software" FORCE)
MARK_AS_ADVANCED( ILC_HOME )

SET( CMAKE_PREFIX_PATH 
        /cvmfs/clicdp.cern.ch/software/FastJet/3.3.2/x86_64-slc6-gcc62-opt;
        /cvmfs/clicdp.cern.ch/software/Xerces-C/3.1.4/x86_64-slc6-gcc62-opt;
        /cvmfs/clicdp.cern.ch/software/Geant4/10.02.p02/x86_64-slc6-gcc62-opt;
        /cvmfs/clicdp.cern.ch/software/ROOT/6.08.00/x86_64-slc6-gcc62-opt;
        /cvmfs/clicdp.cern.ch/software/CLHEP/2.3.1.1/x86_64-slc6-gcc62-opt;
        /cvmfs/clicdp.cern.ch/software/GSL/2.2.1/x86_64-slc6-gcc62-opt;
        ${ILC_HOME}/lcio/HEAD;
        /cvmfs/clicdp.cern.ch/software/Boost/1.62.0/x86_64-slc6-gcc62-opt;
        /cvmfs/clicdp.cern.ch/software/Eigen/3.3.0/x86_64-slc6-gcc62-opt;
        /cvmfs/clicdp.cern.ch/software/Ninja/1.7.1/x86_64-slc6-gcc62-opt;
        ${ILC_HOME}/ilcutil/HEAD;
        ${ILC_HOME}/CondDBMySQL/HEAD;
        ${ILC_HOME}/CED/HEAD;
        ${ILC_HOME}/lccd/HEAD;
        ${ILC_HOME}/Marlin/HEAD;
        ${ILC_HOME}/MarlinDD4hep/HEAD;
        ${ILC_HOME}/DDMarlinPandora/HEAD;
        ${ILC_HOME}/MarlinUtil/HEAD;
        ${ILC_HOME}/MarlinReco/HEAD;
        ${ILC_HOME}/PandoraAnalysis/HEAD;
        ${ILC_HOME}/PandoraPFANew/HEAD;
        ${ILC_HOME}/MarlinPandora/HEAD;
        ${ILC_HOME}/LCFIVertex/HEAD;
        ${ILC_HOME}/LCFIPlus/HEAD;
        ${ILC_HOME}/CEDViewer/HEAD;
        ${ILC_HOME}/Overlay/HEAD;
        ${ILC_HOME}/MarlinFastJet/HEAD;
        ${ILC_HOME}/LCTuple/HEAD;
        ${ILC_HOME}/MarlinKinfit/HEAD;
        ${ILC_HOME}/MarlinTrk/HEAD;
        ${ILC_HOME}/KiTrack/HEAD;
        ${ILC_HOME}/KiTrackMarlin/HEAD;
        ${ILC_HOME}/MarlinTrkProcessors/HEAD;
        ${ILC_HOME}/ILDPerformance/HEAD;
        ${ILC_HOME}/ClicPerformance/HEAD;
        ${ILC_HOME}/ConformalTracking/HEAD;
        ${ILC_HOME}/Physsim/HEAD;
        ${ILC_HOME}/FCalClusterer/HEAD;
        ${ILC_HOME}/ForwardTracking/HEAD;
        ${ILC_HOME}/Clupatra/HEAD;
        ${ILC_HOME}/pathfinder/HEAD;
        ${ILC_HOME}/bbq/HEAD;
        ${ILC_HOME}/Garlic/HEAD;
        ${ILC_HOME}/RAIDA/HEAD;
        ${ILC_HOME}/KalTest/HEAD;
        ${ILC_HOME}/KalDet/HEAD;
        ${ILC_HOME}/GBL/HEAD;
        ${ILC_HOME}/LICH/HEAD;
        ${ILC_HOME}/DD4hep/HEAD;
        ${ILC_HOME}/lcgeo/HEAD;
        ${ILC_HOME}/aidaTT/HEAD;
        ${ILC_HOME}/DDKalTest/HEAD;
        ${ILC_HOME}/gear/HEAD;
CACHE PATH "CMAKE_PREFIX_PATH" FORCE )


option(USE_CXX11 "Use cxx11" OFF)
option(Boost_NO_BOOST_CMAKE "dont use cmake find module for boost" ON)
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O2 -g" CACHE STRING "" FORCE )
set(CMAKE_CXX_STANDARD 14 CACHE STRING "C++ Standard" FORCE)
```

It looks like it was not updated in the mean time

**Comment by petricm** [comment]
No it's not. `/cvmfs/clicdp.cern.ch/iLCSoft/builds/nightly/x86_64-slc6-gcc62-opt` is the install directory and this is not mounted in the container.

**Comment by rete** [comment]
It says exactly:

```
+ Generated cmake build command:
  $  cmake -C /cvmfs/clicdp.cern.ch/iLCSoft/builds/nightly/x86_64-slc6-gcc62-opt/ILCSoft.cmake -DDD4HEP_USE_XERCESC="0" -DCMAKE_CXX_FLAGS_RELWITHDEBINFO="-O2 -g" -DDD4HEP_USE_GEAR="1" -DDD4HEP_USE_LCIO="1" -DBoost_NO_SYSTEM_PATHS="True" -DBOOST_ROOT="/cvmfs/clicdp.cern.ch/software/Boost/1.62.0/x86_64-slc6-gcc62-opt" -DINSTALL_DOC="OFF" -DUSE_CXX11="OFF" -DBoost_NO_BOOST_CMAKE="ON" -DDD4HEP_USE_BOOST="1" -DCMAKE_BUILD_TYPE="RelWithDebInfo" -DDD4HEP_USE_PYROOT="0" -DDD4HEP_USE_GEANT4="1" -DCMAKE_CXX_STANDARD="14" /cvmfs/clicdp.cern.ch/iLCSoft/builds/nightly/x86_64-slc6-gcc62-opt/DD4hep/HEAD
```

**Comment by petricm** [comment]
The container in which this runs, has only the following folders mounted
 - /cvmfs/clicdp.cern.ch/compilers
 - /cvmfs/clicdp.cern.ch/software
is **does not mount** `/cvmfs/clicdp.cern.ch/iLCSoft/` because otherwise I could not install in it. So what ilcinstall sees it's an empty directory.

What you have posted above is the output of the last successful build.

**Comment by petricm** [comment]
The build worked until the merge of #78

**Comment by rete** [comment]
Can you post the full log somewhere ? It looks like the output is screwed up on your link.

**Comment by petricm** [comment]
Sadly this is the output you get when doing this
```
./ilcsoft-install builds/release-ilcsoft.cfg -i 2>&1 | tee ../ilcsoft_gcc.log
```

but you can reproduce the thing by
```
source builds/init_x86_64.sh
 ./ilcsoft-install builds/release-ilcsoft.cfg -i
```

**Comment by rete** [comment]
I got this in my ILCSoft.cmake file:

```cmake
SET( CMAKE_PREFIX_PATH 
        /cvmfs/clicdp.cern.ch/software/Xerces-C/3.1.4/x86_64-slc6-gcc62-opt/lib/cmake/XercesC;
        /cvmfs/clicdp.cern.ch/software/Geant4/10.02.p02/x86_64-slc6-gcc62-opt/lib/Geant4-86.64.6;/cvmfs/clicdp.cern.ch/software/Geant4/10.02.p02/x86_64-slc6-gcc62-opt/lib64/Geant4-86.64.6;
        /cvmfs/clicdp.cern.ch/software/ROOT/6.08.00/x86_64-slc6-gcc62-opt/cmake;
        /cvmfs/clicdp.cern.ch/software/CLHEP/2.3.1.1/x86_64-slc6-gcc62-opt/lib/CLHEP-x86_64-slc6-gcc62-opt;
        ${ILC_HOME}/lcio/HEAD;
        /cvmfs/clicdp.cern.ch/software/Boost/1.62.0/x86_64-slc6-gcc62-opt/lib/cmake/Boost-x86_64-slc6-gcc62-opt;
        /cvmfs/clicdp.cern.ch/software/Eigen/3.3.0/x86_64-slc6-gcc62-opt/share/eigen3/cmake/;
        /cvmfs/clicdp.cern.ch/software/Ninja/1.7.1/x86_64-slc6-gcc62-opt;
        ${ILC_HOME}/ilcutil/HEAD;
        ${ILC_HOME}/CondDBMySQL/HEAD;
        ${ILC_HOME}/CED/HEAD;
        ${ILC_HOME}/lccd/HEAD;
        ${ILC_HOME}/Marlin/HEAD;
        ${ILC_HOME}/MarlinUtil/HEAD;
        ${ILC_HOME}/MarlinReco/HEAD;
        ${ILC_HOME}/PandoraPFANew/HEAD;
        ${ILC_HOME}/LCFIVertex/HEAD;
        ${ILC_HOME}/MarlinTrk/HEAD;
        ${ILC_HOME}/KiTrack/HEAD;
        ${ILC_HOME}/KiTrackMarlin/HEAD;
        ${ILC_HOME}/pathfinder/HEAD;
        ${ILC_HOME}/RAIDA/HEAD;
        ${ILC_HOME}/KalTest/HEAD;
        ${ILC_HOME}/KalDet/HEAD;
        ${ILC_HOME}/GBL/HEAD;
        /nfs/dust/ilc/user/eteremi/iLCSoft/Marko_issue/DD4hep/HEAD/cmake;
        ${ILC_HOME}/aidaTT/HEAD;
        ${ILC_HOME}/DDKalTest/HEAD;
        ${ILC_HOME}/gear/HEAD;
CACHE PATH "CMAKE_PREFIX_PATH" FORCE )
```

The issue is the Geant4 version here, wrongly set to `86.64.6` in the cmake config path.

**Comment by rete** [comment]
The `use()` constructs in baseilc.py tries to guess the version from the basename of the install path:

See : https://github.com/iLCSoft/iLCInstall/blob/master/ilcsoft/baseilc.py#L246

Which is true for all installations we make except the nightly builds.
We could check whether we are running a nightly and try to build the version out of the path provided in the `use()` construct.

Does that seem a good solution ?

**Comment by petricm** [comment]
So you say, that you can only use ilcinstall with `use()` for a particular folder structure, and this is an implicit source code condition? I don't think this is a good idea.

I don't see that the nightly case is any different from using this `/cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/geant4/10.02.p02/`

**Comment by rete** [comment]
Nightly case: `/cvmfs/clicdp.cern.ch/software/Geant4/10.02.p02/x86_64-slc6-gcc62-opt`
The path you provided: `/cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/geant4/10.02.p02/`

The code run in the case of `use()` looks for the version in the base name of this path. For the nightly build, it is extracting `x86_64-slc6-gcc62-opt`, giving a version of `86.64.6`.
This is why I'm suggesting this solution. Not the best though...

**Comment by gaede** [comment]
To add my two cents:  we should not rely on any assumption about the path - at least not without a well defined way of overwriting it.
What I do not understand the corresponding code in baseilc.py has not been touched and was like that for many years. @petric have you changed sth. in your nightly configuration ?
Can we not easily take the version number provided in the config files ?

**Comment by petricm** [comment]
>To add my two cents: we should not rely on any assumption about the path - at least not without a well defined way of overwriting it.

completely agree
> What I do not understand the corresponding code in baseilc.py has not been touched and was like that for many years. @petric have you changed sth. in your nightly configuration ?

No there was no change. The nightly failure started after the merge of #78

> Can we not easily take the version number provided in the config files ?

This is a better solution then relying on the path.

**Comment by rete** [comment]
> No there was no change. The nightly failure started after the merge of #78

Yes because the version was not use in the case the package is `use()`d. Now for geant4 we want to use this version string to point to the correct cmake config file. This is why it is breaking now.

> Can we not easily take the version number provided in the config files ?
> This is a better solution then relying on the path.

So we need a solution to pass both the path and the version to the package on creation. Note that cases like:
- path = `/cvmfs/clicdp.cern.ch/software/Geant4/10.02.p02/x86_64-slc6-gcc62-opt`
- version = `10.04.p03`

won't throw any error. You'll to make sure that the version you are pointing to has the same version has you pass in the path.

**Comment by petricm** [comment]
Now the compilation passes DD4hep but it fails at KalTest, because some ROOT macros are missing 
```
/bin/sh: ROOT_CINT_EXECUTABLE-NOTFOUND: command not found
```

https://gitlab.cern.ch/CLICdp/SoftwareConfigurations/iLCSoft/-/jobs/6457069

**Comment by gaede** [comment]
Please try to include this in your version (sourcing of the build_env.sh) :
https://github.com/iLCSoft/iLCInstall/pull/79/commits/54e1efc6b80500c7b4fb00ededc0c225ed3dd2e6

**Comment by rete** [comment]
@petricm Any success ?

**Comment by petricm** [comment]
Sorry I don't understand this comment, the nightly always uses the last checkout of master, so this should be present.

**Comment by petricm** [comment]
Now the problem is in KalDet, #86 is incomplete.
https://gitlab.cern.ch/CLICdp/SoftwareConfigurations/iLCSoft/-/jobs/6472471

**Comment by petricm** [comment]
Not there is a problem in MarlinKinFit
```
-- Check for MarlinUtil_MARLINUTIL_LIBRARY: /cvmfs/clicdp.cern.ch/iLCSoft/builds/nightly/x86_64-slc6-gcc62-opt/MarlinUtil/HEAD/lib/libMarlinUtil.so -- ok
-- Check for MarlinUtil_MARLINUTILANN_LIBRARY: /cvmfs/clicdp.cern.ch/iLCSoft/builds/nightly/x86_64-slc6-gcc62-opt/MarlinUtil/HEAD/lib/libMarlinUtilAnn.so -- ok
-- Found MarlinUtil: /cvmfs/clicdp.cern.ch/iLCSoft/builds/nightly/x86_64-slc6-gcc62-opt/MarlinUtil/HEAD (Required is at least version "1.4") 
CMake Error at CMakeLists.txt:48 (FIND_PACKAGE):
  By not providing "FindMarlinKinfit.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "MarlinKinfit", but CMake did not find one.

  Could not find a package configuration file provided by "MarlinKinfit"
  (requested version 0.0) with any of the following names:

    MarlinKinfitConfig.cmake
    marlinkinfit-config.cmake

  Add the installation prefix of "MarlinKinfit" to CMAKE_PREFIX_PATH or set
  "MarlinKinfit_DIR" to a directory containing one of the above files.  If
  "MarlinKinfit" provides a separate development package or SDK, be sure it
  has been installed.
```

https://gitlab.cern.ch/CLICdp/SoftwareConfigurations/iLCSoft/-/jobs/6487208

**Comment by petricm** [comment]
@rete can you look at this please.

**Comment by rete** [comment]
@petricm Can you re-trigger the nightly please ?
